services:
  database:
    image: postgres:alpine
    container_name: bookstore-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./server/postgres:/docker-entrypoint-initdb.d

  core_service:
    build: ./server/core
    container_name: bookstore-core
    ports:
      - 8080:8080
    depends_on:
      - database

  sentence_analyzer:
    build: ./server/sentence-analyzer
    container_name: bookstore-sentence-analyzer
    ports:
      - 8081:8081
    depends_on:
      - core_service
