services:
  database:
    image: postgres:alpine
    container_name: bookstore_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./server/postgres:/docker-entrypoint-initdb.d

  core_service:
    build: ./server/core
    container_name: bookstore_core
    ports:
      - 8080:8080
    depends_on:
      - database
